name: restaurant_app
description: "A new Flutter project."
publish_to: "none"
version: 1.1.7+22

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  app_links: ^6.3.2
  app_tracking_transparency: ^2.0.6+1
  cached_network_image: ^3.4.1
  card_swiper: ^3.0.1
  cloud_firestore: ^5.4.2
  cloud_functions: ^5.1.3
  connectivity_plus: ^6.0.5
  dartz: ^0.10.1
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  file_picker: ^9.0.1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_messaging: ^15.2.4
  firebase_storage: ^12.0.1
  fl_chart: ^0.69.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_image_compress: ^2.3.0
  flutter_launcher_icons: ^0.14.3
  flutter_local_notifications: ^19.0.0
  flutter_otp_text_field: ^1.1.3+2
  flutter_polyline_points: ^2.0.0
  flutter_stepindicator: ^0.1.7
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.12
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.11.0
  http: ^1.2.1
  image_cropper: ^9.0.0
  image_picker: ^1.1.1
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  introduction_screen: ^3.1.14
  lottie: ^3.1.2
  path: ^1.9.0
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  pin_code_fields: ^8.0.1
  provider: ^6.1.2
  razorpay_flutter: ^1.4.0
  share_plus: ^10.1.2
  shared_preferences: ^2.2.3
  sizer: ^2.0.15
  sliding_up_panel: ^2.0.0+1
  speech_to_text: ^7.0.0
  syncfusion_flutter_signaturepad: ^28.2.7
  upgrader: ^11.3.1
  video_player: ^2.9.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/appicon.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/images/introduction/
    - assets/images/socials/
    - assets/animations/

