name: user_app
description: "A new Flutter project."
publish_to: "none"
version: 1.1.11+26


environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  another_stepper: ^1.2.2
  card_swiper: ^3.0.1
  customizable_counter: ^1.0.4
  dotted_line: ^3.2.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_otp_text_field: ^1.1.3+2
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.10+1
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.1
  intl_phone_field: ^3.2.0
  introduction_screen: ^4.0.0
  overlapped_carousel: ^1.0.2
  popover: ^0.3.0
  shared_preferences: ^2.2.3
  sizer: ^3.1.3
  dartz: ^0.10.1
  flutter_launcher_icons: ^0.14.4
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  lottie: ^3.1.2
  vibration: ^3.1.3
  pin_code_fields: ^8.0.1
  permission_handler: ^12.0.1
  flutter_polyline_points: ^3.0.1
  razorpay_flutter: ^1.4.0
  http: ^1.2.2
  speech_to_text: ^7.3.0
  intl: ^0.20.2
  cloud_firestore: ^6.0.1
  fluttertoast: ^8.2.8
  image_picker: ^1.1.2
  firebase_storage: ^13.0.1
  cached_network_image: ^3.4.1
  flutter_background: ^1.2.0
  cloud_functions: ^6.0.1
  provider: ^6.1.2
  share_plus: ^11.1.0
  app_links: ^6.3.2
  photo_view: ^0.15.0
  video_player: ^2.9.2
  upgrader: ^11.3.1
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.0.0
  url_launcher: ^6.3.1
  # app_tracking_transparency: ^2.0.6+1
  
  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appicon1.png"
  min_sdk_android: 21 
  

# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/images/appIcon.png"
#   min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0



flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/images/introduction/
    - assets/images/socials/
    - assets/images/ads/
    - assets/animations/
    - assets/food/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf